# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

feRcpp <- function(valueOverThreshold, M1, M2, M3) {
    .Call(`_test10_feRcpp`, valueOverThreshold, M1, M2, M3)
}

#' @useDynLib test10, .registration=TRUE
maxminRcpp <- function(matrix_1, matrix_2) {
    .Call(`_test10_maxminRcpp`, matrix_1, matrix_2)
}

